env:
  es6: true
  browser: true
  jest: true
  node: true

parserOptions:
  ecmaVersion: 2020  # ECMAScript 6 (2015)
  sourceType: module  # Habilitar módulos ES6 (import/export)

globals:
  PR: true
  "structuredClone": "readonly"
extends:
  - eslint:recommended
  - plugin:jest/recommended
  #- plugin:fp/recommended
plugins:
  - jest
  - fp

rules:
  semi: [error, always]
  no-unused-vars: ["warn", { "varsIgnorePattern": "^_" }]
  no-prototype-builtins: off
  "no-console": "off"
  no-useless-escape: off
  fp/no-mutation: off  # Desactiva errores por mutación
  fp/no-let: off
  quotes: [error, 'single']  # Obliga uso de comillas simples
  max-len: [warn, { code: 120 }]  # Aumenta límite de longitud de línea
  no-trailing-spaces: error
  indent: [error, 2]
  comma-dangle: [error, 'always-multiline']
  space-infix-ops: error


ignorePatterns:
  - coverage/