env:
  es6: true
  browser: true
  jest: true
  node: true

parserOptions:
  ecmaVersion: 2015  # ECMAScript 6 (2015)
  sourceType: "module"  # Habilitar módulos ES6 (import/export)

globals:
  PR: true

extends:
  - eslint:recommended
  - plugin:jest/recommended
plugins:
  - jest

rules:
  semi: [error, always]
  quotes: [error, double]
  no-unused-vars: ["warn", { "varsIgnorePattern": "^_" }]
  no-prototype-builtins: off
  "no-console": "off"
  no-useless-escape: off

ignorePatterns:
  - coverage/